#name: Docker Lint
#on: [push]
#jobs:
#  lint:
#    runs-on: ubuntu-latest
#    steps: 
#    - name: Checkout
#      uses: actions/checkout@master
#    - name: Docker Lint
#      uses: luke142367/Docker-Lint-Action@v1.1.1
#      with:
#        target: Dockerfile
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
